#!/usr/bin/env bash
# Generate .clangd for ESP-IDF cross-builds edited with host clangd.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
IDF_PATH="${IDF_PATH:-${HOME}/esp/esp-idf}"

if [[ ! -d "${IDF_PATH}/components/newlib/platform_include" ]]; then
  echo "error: IDF newlib headers not found at ${IDF_PATH}/components/newlib/platform_include" >&2
  echo "Set IDF_PATH to your esp-idf checkout." >&2
  exit 1
fi

if [[ ! -f "${ROOT}/example/esp32-sync-http/build/compile_commands.json" ]]; then
  echo "error: compile_commands.json missing. Run: cd example/esp32-sync-http && idf.py build" >&2
  exit 1
fi

cat >"${ROOT}/.clangd" <<EOF
# Generated by scripts/setup-clangd.sh — re-run after toolchain/IDF updates.

CompileFlags:
  Remove:
    - -mlongcalls
    - -fno-shrink-wrap
    - -fno-tree-switch-conversion
    - -fstrict-volatile-bitfields
    - -fno-jump-tables
    - -mtext-section-literals
    - -mdisable-hardware-atomics
  Add:
    # Host clang is not Xtensa; use GCC sysroot via --query-driver in VS Code.
    - -D__XTENSA__
    # Do not add host /usr/include; avoids ssize_t / newlib typedef clashes.
    - -nostdinc

Diagnostics:
  # Host clang + Xtensa newlib/lwIP can disagree on ssize_t (int vs long). Harmless for IDE.
  Suppress:
    - redefinition_different_typedef

---
If:
  PathMatch: .*/(example/esp32-sync-http|src|include)/.*
CompileFlags:
  CompilationDatabase: example/esp32-sync-http/build

---
If:
  PathMatch: .*/(include|src)/.*
CompileFlags:
  Add:
    - -I${ROOT}/include
    - -I${ROOT}/src
EOF

ln -sf example/esp32-sync-http/build/compile_commands.json "${ROOT}/compile_commands.json"

echo "Wrote ${ROOT}/.clangd"
echo "Symlinked compile_commands.json -> example/esp32-sync-http/build/"
echo ""
echo "Ensure .vscode/settings.json passes --query-driver for xtensa-esp-elf-gcc."
